/// <reference path="../pb_data/types.d.ts" />

// 修行人著述 — adds bilingual (English) fields to the articles collection and
// seeds two original articles under 清凉月老师 (qingliangyue):
//   1. 《禅宗的实证步骤》  — The Empirical Steps of Chan Buddhism
//   2. 《佛学要旨，心地法门》 — The Essentials of Buddhism: The Mind-Ground Method
// The Chinese original text is preserved verbatim; an English translation is
// provided as a language-switchable counterpart of the same article.

migrate(
  (app) => {
    const articles = app.findCollectionByNameOrId("articles");

    // 1. Add bilingual English fields (idempotent).
    const addText = (name, max) => {
      if (!articles.fields.getByName(name)) {
        articles.fields.add(new TextField({ name, max }));
      }
    };
    addText("titleEn", 200);
    addText("categoryEn", 100);
    addText("tagsEn", 300);
    addText("excerptEn", 500);
    addText("overviewEn", 2000);
    if (!articles.fields.getByName("bodyEn")) {
      articles.fields.add(new EditorField({ name: "bodyEn" }));
    }
    app.save(articles);

    const now = new Date().toISOString().replace("T", " ").substring(0, 19) + ".000Z";

    // Helper: wrap an array of paragraph strings into <p> HTML, preserving text verbatim.
    const paras = (arr) => arr.map((p) => `<p>${p}</p>`).join("");

    const items = [
      {
        // ── 文章 1 ──
        slug: "qingliangyue-chan-steps",
        title: "禅宗的实证步骤",
        titleEn: "The Empirical Steps of Chan Buddhism",
        author: "qingliangyue",
        category: "禅宗",
        categoryEn: "Chan Buddhism",
        tags: "禅宗,实证,明心见性,如来藏,清凉月",
        tagsEn: "Chan,Empirical Practice,Seeing Nature,Tathāgatagarbha,Qingliangyue",
        excerpt:
          "清凉月老师对禅宗修行次第的概括讲解：从明心破初参，到回归如来藏的大彻大悟，再到证入八地的物质自在，三步原理清晰可循。",
        excerptEn:
          "A summary by Qingliangyue of the Chan path of practice: from clarifying the mind and breaking the first barrier, to the great awakening of returning to the Tathāgatagarbha, and finally to the freedom of matter at the eighth stage — three steps with a clear underlying principle.",
        overview:
          "本文为清凉月老师关于禅宗实证步骤的原创概述。禅宗并非神秘莫测，其原理与观青色青光一致：当前状态本由如来藏生成，如来藏的一切特征当前状态皆有，差别只在于能否恒定、稳定、深刻地展现。文章梳理明心破初参、回归如来藏的大彻大悟、以及证入八地得物质自在这三步，并指出其与佛教一般修行次第相通。",
        overviewEn:
          "This is an original overview by Qingliangyue on the empirical steps of Chan. Chan is not mysterious; its principle is the same as contemplating blue light: our present state is generated by the Tathāgatagarbha, and every feature of the Tathāgatagarbha is already present here — the only difference is whether those features can manifest constantly, stably, and deeply. The article outlines three steps — clarifying the mind and breaking the first barrier, the great awakening of returning to the Tathāgatagarbha, and attaining freedom of matter at the eighth stage — and notes their correspondence with the general Buddhist path.",
        body: paras([
          "禅宗是什么？什么是破初参和大彻大悟？禅宗的修行步骤是什么？",
          "有的人总是觉得这个禅宗是个稀奇古怪的东西，好像神秘得不得了，其实它没什么神秘的，和观青色青光原理完全是一样的，就是通过相应的方法进行。因为我们当前这种状态也是由如来藏生成的，如来藏的所有的特征，我们当前这种状态都有，你与诸佛一点不差，诸佛有的东西，你也有，你与诸佛错在哪里？就错在人家那个状态，特征，全部都能够展现出来，能够恒定的、稳定的、深刻地展现出来，你不能，唯一的就错在这个地方。",
          "所以一定要掌握这一点，要不然人家告诉你，你本来就是佛，哎呀我不是佛，你一点都不敢承认的。",
          "禅宗就是告诉你当前这种状态，哪些特征是如来藏展现出来的，就是古人说的“六根门头，放光动地”，哪些特征是如来藏展现出来的，然后你去安住于这个特征，让时间延续。",
          "所以第一步就是，人家告诉你，哪些特征是如来藏展现出来的，你经过这样的点，点，点，你终于知道，哦，原来这些特征是如来藏展现出来的，这叫什么？这叫明心，破初参，第一关你过了，你知道该怎样用功了，心该怎样用了，修行该怎样用功了，这仅仅只是第一关。",
          "第二关你在干什么？你就必须唯一的安住于这个特征，然后通过这个特征，你回归如来藏，这才是真正的大彻大悟了，只有回归如来藏才大彻大悟，前面的那个仅仅只是明心而已，后面的才回归如来藏，咱们说明心见性，这一关过了之后，叫做完成了一个思维的回归，也就我们证入了如来藏。",
          "思维方面解决了，但物质方面的应用你还没有真正掌握，于是还有最后一步，你要完成物质方面应用，就是证入八地，最后一个叫百尺竿头，更进一步，没有最后这一步也是不行的，也是你成功不了的，也就是说禅宗的修行，这三步也是按照这样的原理去进行。",
          "那么这三步你也看得出，和佛教的一般的修行都是一样的，都是先证入初地，先证入回归如来藏，然后再证入八地，证得意生身，获得一个物质的自由，这就是我们的实证最基本的原理，一定要掌握，掌握这个原理之后，你就知道该怎么做了。",
        ]),
        bodyEn: paras([
          "What is Chan? What does it mean to break the first barrier and to attain great awakening? What are the steps of Chan practice?",
          "Some people always feel that Chan is something bizarre and impossibly mysterious. In fact it is not mysterious at all — its principle is exactly the same as contemplating blue light: one proceeds by means of a corresponding method. Because our present state is also generated by the Tathāgatagarbha, every feature of the Tathāgatagarbha is already present in our current state. You are no different from the Buddhas: what the Buddhas have, you also have. Where do you differ from them? Only in that, in their state, all the features can manifest — constantly, stably, and deeply — whereas you cannot. That is the sole difference.",
          "So you must grasp this point; otherwise, when someone tells you that you are already a Buddha, you will say, \"Oh, I am not a Buddha,\" and not dare to acknowledge it at all.",
          "Chan simply tells you which features of your current state are manifestations of the Tathāgatagarbha — what the ancients called \"radiating light and shaking the earth at the gates of the six senses.\" Once you know which features are manifestations of the Tathāgatagarbha, you abide in that feature and let time continue.",
          "So the first step is: someone points out to you which features are manifestations of the Tathāgatagarbha. Through such pointing, again and again, you finally realize — oh, so these features are manifestations of the Tathāgatagarbha. What is this called? It is called clarifying the mind, breaking the first barrier. You have passed the first gate: you now know how to apply effort, how the mind should be used, and how practice should proceed. This is only the first gate.",
          "What do you do in the second gate? You must abide exclusively in this feature, and through this feature you return to the Tathāgatagarbha. Only this is true great awakening — only returning to the Tathāgatagarbha is great awakening. The earlier step was merely clarifying the mind; the later step is returning to the Tathāgatagarbha. We speak of \"clarifying the mind and seeing one's nature.\" Once this gate is passed, it is called completing the return of thinking — that is, we have entered the Tathāgatagarbha.",
          "The aspect of thinking is resolved, but you have not yet truly mastered the application of matter, so there is one final step: you must complete the application of matter, which is entering the eighth stage. The last is called \"a further step beyond the top of the hundred-foot pole.\" Without this final step it will not do, and you will not succeed. In other words, the practice of Chan proceeds through these three steps according to this same principle.",
          "As you can see, these three steps are the same as general Buddhist practice: first one enters the first stage, first returns to the Tathāgatagarbha, and then enters the eighth stage, attains the mind-made body, and gains freedom of matter. This is the most fundamental principle of empirical practice. You must grasp it; once you do, you will know what to do.",
        ]),
        related: "qingliangyue-zhiguan-intro,qingliangyue-breath-mind",
      },
      {
        // ── 文章 2 ──
        slug: "qingliangyue-xindi-famen",
        title: "佛学要旨，心地法门",
        titleEn: "The Essentials of Buddhism: The Mind-Ground Method",
        author: "qingliangyue",
        category: "心地法门",
        categoryEn: "Mind-Ground Method",
        tags: "佛学,心地法门,专注力,如来藏,清凉月",
        tagsEn: "Buddhism,Mind-Ground,Concentration,Tathāgatagarbha,Qingliangyue",
        excerpt:
          "清凉月老师以双层灯笼为喻，系统讲解佛学心地法门：真心如烛光，第六识意识与第七识末那识如灯笼纸，实证即是从污染心念回归清净心光的完整心路历程。",
        excerptEn:
          "Using the metaphor of a double-layered lantern, Qingliangyue systematically explains the Buddhist mind-ground method: the true mind is like the candle flame within, while the sixth consciousness and the seventh consciousness are like the lantern paper. Practice is the complete inner journey from defiled thoughts back to the pure light of mind.",
        overview:
          "本文为清凉月老师关于佛学心地法门的原创概述。佛学以科学的实证精神，助人获得心理的根本解脱与身体的康复。文章以双层灯笼为喻：烛光代表真心、如来藏，红绿两层灯笼纸分别代表第六识意识与第七识末那识，并分三步讲述从培养专注力、放下念头到体会念头与思想之别的心路历程。",
        overviewEn:
          "This is an original overview by Qingliangyue on the Buddhist mind-ground method. With its scientific spirit of empirical practice, Buddhism helps one attain fundamental liberation of mind and recovery of body. Using the metaphor of a double-layered lantern — the candle flame as the true mind and Tathāgatagarbha, the red and green lantern paper as the sixth and seventh consciousnesses — the article describes in three steps the inner journey from cultivating concentration, to releasing thoughts, to experiencing the difference between thoughts and awareness.",
        body: paras([
          "佛学以其科学的实证精神，使后来的人们能够通过对佛学的学习，得到心理上的根本解脱，同时也使身体得到最大限度的康复，正是因为佛学心地法门对人类身心健康的卓有成效的探索，使得我们现代人能在这物欲横流的享受主义盛行的时代，得到一份世外桃源般的清凉，找到一个心灵的避风港。下面就借助上图系统讲述一下佛学的核心理论：心地法门。",
          "上图是一个双层灯笼，里面的烛光，代表我们心理的本来状态，也就是我们常说的真心、如来藏、本来面目、菩提、禅、真如、如如、觉、大悲心、自性等等。外面的两层灯笼纸，红色的代表第六识意识，绿色的代表第七识末那识。",
          "第六识意识指的是心理活动的相续性，比如你对某人一见钟情，你会控制不住的茶里饭里都是他，心就像脱缰的野马一样停不下来，这就是意的相续性。而第七识则是分别执着识，你吃饭的时候总要忍不住分别好吃还是不好吃，好吃的你就忍不住要喜欢，当然不好吃的你会如食锯末、味同嚼蜡，这就是分别执着。图上箭头代表我们实证过程中的心路历程。",
          "我们平常的人就生活在灯笼外面的心理状态，清净无染的心光从里面透出来，经过六七两识的污染，就变成了红绿两种颜色，这就迫使你不得不成为心的奴隶，任凭心理咨询师怎样善说六国的剖析解释，任凭阿Q怎样无敌的法宝精神胜利法，对你都无济于事，因为你毕竟处在水生火热中，那些人不过是在岸上鼓励你要挺住，画饼岂能充饥，望梅真的能止渴么？受过巨大心灵创伤的人最能体会心死的感觉。",
          "怎样使自己能够自主心灵呢？怎样能够使自己真的成为自己心理活动的主人呢？这就是佛学心地法门的根本任务。这里简要介绍一下方法，如果有兴趣深究，我们其他的几篇文章可以作为参考。",
          "第一步 培养专注力。持续的长时间的专心致志的观想一个动作或一个物体，也可以听一种声音等等都可以。就这样渐次达到一种毫无身体感觉的状态。到了这时候，你就会很清楚的看到前一个念头下去，隔了一会后一个念头才会出来。念头的相续性彻底被消灭了，也就是说意根伏下了。",
          "第二步 接上面，每出一个念头，你都要清清楚楚的看到它，然后用轻柔的心放下它，你会发现念头与念头之间的时间距离越来越长。这时候你用无我的思想想象把自己和整个大自然融合在一起，你会发现念头没有了，而你心里却清清楚楚，思想很活跃，你终于第一次体会到念头和思想并不总是一回事，你同时还会发现你再也不会生气了，尽管你试图是自己再生气起来，但你发现那是多么困难的一件事。",
          "第三步 达到第二步的人往往很怀念以前能生气的状态，这就是习气，他于是竭尽全力去想象生气是怎麽一回事，进过一番刻苦和努力，终于他发现一种心力明显动起来，紧跟着就产生第一个念头“我”，紧接着就是“他”，随后就是成对成对相互对立的念头相续出现，比如爱与恨、喜欢与厌恶等，这就是第七识，发展下去你会盯着一件印象最深的具体的事情连续地想下去，这就是第六识，你终于又回到以前的病态心理活动状态中了。",
          "这就是佛学整个心地法门的心路历程，它难道不是一副治疗心理疾病的良药吗？它能从根本上治疗你的心理疾病，让你做自己心灵的主人，这是任何通常意义上的心理学所无法做到的。",
        ]),
        bodyEn: paras([
          "With its scientific spirit of empirical practice, Buddhism enables later generations to attain fundamental liberation of mind through the study of Buddhism, and at the same time to bring about the greatest possible recovery of the body. It is precisely because the Buddhist mind-ground method has carried out such fruitful exploration of human physical and mental health that we modern people, in an age awash with material desire and the prevalence of hedonism, can obtain a tranquility like that of a utopian refuge and find a safe haven for the mind. Let us now use the diagram above to systematically explain the core theory of Buddhism: the mind-ground method.",
          "The diagram above is a double-layered lantern. The candle flame inside represents the original state of our mind — what we commonly call the true mind, the Tathāgatagarbha, the original face, bodhi, Chan, true thusness, suchness, awareness, the mind of great compassion, self-nature, and so on. The two outer layers of lantern paper represent the sixth consciousness (consciousness, red) and the seventh consciousness (manas, green).",
          "The sixth consciousness refers to the continuity of mental activity. For example, when you fall in love at first sight with someone, you cannot help thinking of them in everything you do — your mind is like a runaway horse that cannot stop. This is the continuity of consciousness. The seventh consciousness is the discriminating and clinging consciousness: when you eat, you cannot help distinguishing between delicious and not delicious; what is delicious you cannot help liking, while what is not delicious feels like chewing sawdust — this is discrimination and clinging. The arrows in the diagram represent the inner journey of our empirical practice.",
          "We ordinary people live in the mental state on the outside of the lantern. The pure, undefiled light of mind shines from within, but after passing through the contamination of the sixth and seventh consciousnesses it becomes the two colors red and green. This forces you to become a slave of your mind. No matter how eloquently a psychological counselor analyzes and explains, and no matter how invincible Ah Q's spiritual victory method may be, none of it helps you — because you are, after all, in deep water and hot fire; those people are merely on the shore encouraging you to hold on. Can a painted pie satisfy hunger? Can gazing at plums truly quench thirst? Those who have suffered great psychological trauma know best the feeling of a dead heart.",
          "How can one become master of one's own mind? How can one truly become the master of one's own mental activity? This is the fundamental task of the Buddhist mind-ground method. Here is a brief introduction to the method; if you wish to delve deeper, several of our other articles may serve as references.",
          "Step One: Cultivate concentration. Continuously and for a long time, single-mindedly contemplate one action or one object, or listen to a sound, and so on. In this way, gradually reach a state in which there is no bodily sensation at all. At this point, you will clearly see one thought subside, and only after a gap will the next thought arise. The continuity of thoughts is completely eliminated — in other words, the faculty of consciousness is subdued.",
          "Step Two: Continuing from above, each time a thought arises, you must see it with perfect clarity, then release it with a gentle mind. You will find that the interval between thoughts grows longer and longer. At this point, use the thought of selflessness to imagine merging yourself with all of nature. You will find that thoughts disappear, yet your mind remains perfectly clear and your awareness is very active. For the first time, you realize that thoughts and awareness are not always the same thing. At the same time, you will find that you can no longer get angry — even if you try to make yourself angry again, you discover how difficult that is.",
          "Step Three: Those who have reached the second step often miss the former state in which they could get angry — this is habitual tendency. So they exert all their effort to imagine what anger is like. After a period of arduous effort, they finally find that a mental force clearly begins to move, immediately followed by the first thought, \"I,\" then \"he,\" and then pairs of opposing thoughts arise in succession — love and hate, liking and dislike, and so on. This is the seventh consciousness. As it develops, you will fixate on one specific, most impressive matter and think about it continuously — this is the sixth consciousness. You have finally returned to the former state of pathological mental activity.",
          "This is the entire inner journey of the Buddhist mind-ground method. Is it not a fine medicine for treating psychological illness? It can cure your psychological illness at its root and let you become the master of your own mind — something that no ordinary psychology can accomplish.",
        ]),
        related: "qingliangyue-zhiguan-intro,qingliangyue-chan-steps",
      },
    ];

    for (const item of items) {
      try {
        app.findFirstRecordByData("articles", "slug", item.slug);
        continue; // already exists
      } catch (_) {}

      const r = new Record(articles);
      r.set("type", "wiki");
      r.set("status", "published");
      r.set("publishAt", now);
      r.set("seoTitle", `${item.titleEn} — Practitioner Writings | Spirit Root`);
      r.set("metaDescription", item.excerptEn);
      for (const k in item) r.set(k, item[k]);
      app.save(r);
    }
  },
  (app) => {
    const slugs = ["qingliangyue-chan-steps", "qingliangyue-xindi-famen"];
    for (const slug of slugs) {
      try {
        const r = app.findFirstRecordByData("articles", "slug", slug);
        app.delete(r);
      } catch (_) {}
    }
  },
);
