// Auto-generated from PocketBase SQLite export
const articlesData = [
  {
    "body": "<p>The Spirit Root is one of the most fundamental concepts in cultivation fiction. It describes a person's inborn affinity with the five elements (metal, wood, water, fire, earth) and their ability to draw in and refine <em>Qi</em>.</p><p>A cultivator with a pure, single-element Spirit Root is considered a genius, while those with mixed or 'waste' roots must rely on effort, opportunity, or artificial means to progress.</p>",
    "category": "Xianxia Basics",
    "cover": "https://images.hostinger.com/4f95e416-0038-4850-ad03-ef020a97f03b.png",
    "created": "2026-07-26 04:38:48.304Z",
    "excerpt": "The innate foundation that determines one's capacity to cultivate in Xianxia fiction.",
    "historical": "<p>While the term is a modern literary invention, it draws on older Daoist ideas of innate constitution (禀赋) and the belief that spiritual attainment depends on both nature and cultivation practice.</p>",
    "id": "udt8hasqam042ow",
    "metaDescription": "What is a Spirit Root in Xianxia fiction? An introduction to lingen, the innate talent for cultivation.",
    "ogImage": "",
    "overview": "In Xianxia fiction, a Spirit Root (灵根, línggēn) is the innate constitution that determines whether — and how well — a person can absorb spiritual energy and walk the path of cultivation.",
    "publishAt": "2026-07-26 04:38:48.000Z",
    "related": "qi,golden-core,cultivation-realms",
    "seoTitle": "Spirit Root — Xianxia Cultivation Explained | Spirit Root",
    "slug": "spirit-root",
    "status": "published",
    "tags": "spirit root, linggen, cultivation, talent",
    "title": "Spirit Root",
    "type": "wiki",
    "updated": "2026-07-26 04:38:48.304Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>In cultivation stories, gathering and refining Qi is the first step on the immortal path. Cultivators breathe, meditate, and circulate Qi through meridians to strengthen the body and spirit.</p><p>The concept is rooted in genuine Chinese medicine, Daoist internal alchemy, and Qigong practice.</p>",
    "category": "Cultivation Concepts",
    "cover": "https://images.hostinger.com/073781d0-3ccf-4bfa-8c41-ea98ce86e8cd.png",
    "created": "2026-07-26 04:38:48.305Z",
    "excerpt": "The vital energy that flows through all things and fuels cultivation.",
    "historical": "<p>Qi has been central to Chinese philosophy, medicine, and martial arts for over two thousand years, appearing in texts from the Huangdi Neijing to Daoist alchemical manuals.</p>",
    "id": "yq9g2yfi96hjm8x",
    "metaDescription": "Understand Qi, the vital energy behind Xianxia cultivation and Chinese traditional practice.",
    "ogImage": "",
    "overview": "Qi (气) is the vital energy or life-force that, in both fiction and traditional Chinese thought, animates the body and the cosmos alike.",
    "publishAt": "2026-07-26 04:38:48.000Z",
    "related": "spirit-root,neidan,qigong",
    "seoTitle": "Qi — Vital Energy in Cultivation | Spirit Root",
    "slug": "qi",
    "status": "published",
    "tags": "qi, energy, breath, vital force",
    "title": "Qi",
    "type": "wiki",
    "updated": "2026-07-26 04:38:48.305Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>Reaching the Golden Core stage vastly extends lifespan and power. The formation of the core is often the most dangerous breakthrough in a cultivator's early journey.</p><p>The imagery derives directly from Daoist internal alchemy (Neidan), where the 'golden elixir' symbolizes spiritual perfection.</p>",
    "category": "Cultivation Realms",
    "cover": "https://images.hostinger.com/4706bfbe-2b15-4959-b4c3-154ee726fa1b.png",
    "created": "2026-07-26 04:38:48.305Z",
    "excerpt": "A major cultivation realm where condensed Qi forms a solid core of energy.",
    "historical": "<p>Jindan is a real term from Daoist alchemy, describing the inner elixir cultivated through meditation, breath, and moral refinement rather than a literal pill.</p>",
    "id": "f9c75yic156sa7a",
    "metaDescription": "The Golden Core realm explained: how cultivators condense Qi into a core, and its Daoist roots.",
    "ogImage": "",
    "overview": "The Golden Core (金丹, jīndān) realm marks a decisive threshold where a cultivator condenses years of gathered Qi into a solid, radiant core.",
    "publishAt": "2026-07-26 04:38:48.000Z",
    "related": "nascent-soul,neidan,cultivation-realms",
    "seoTitle": "Golden Core — Cultivation Realm | Spirit Root",
    "slug": "golden-core",
    "status": "published",
    "tags": "golden core, jindan, realm, breakthrough",
    "title": "Golden Core",
    "type": "wiki",
    "updated": "2026-07-26 04:38:48.305Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>A typical progression runs: Qi Condensation, Foundation Establishment, Golden Core, Nascent Soul, Soul Formation, and beyond toward ascension. Each realm brings longer life, greater strength, and deeper insight into the Dao.</p>",
    "category": "Cultivation Realms",
    "cover": "https://images.hostinger.com/4087246a-2032-4fd3-8a66-7b61c27152ae.png",
    "created": "2026-07-26 04:38:48.305Z",
    "excerpt": "The staged ladder of power that structures nearly every Xianxia story.",
    "historical": "<p>The tiered structure echoes Daoist and Buddhist maps of spiritual progress, reframed as a game-like ladder for narrative momentum.</p>",
    "id": "j86i1poeqkwjfpp",
    "metaDescription": "A guide to the cultivation realms of Xianxia fiction, from Qi Condensation to Nascent Soul.",
    "ogImage": "",
    "overview": "Cultivation Realms are the sequential stages of spiritual attainment through which a cultivator ascends toward immortality.",
    "publishAt": "2026-07-26 04:38:48.000Z",
    "related": "golden-core,nascent-soul,dao-heart",
    "seoTitle": "Cultivation Realms Explained | Spirit Root",
    "slug": "cultivation-realms",
    "status": "published",
    "tags": "realms, stages, progression",
    "title": "Cultivation Realms",
    "type": "wiki",
    "updated": "2026-07-26 04:38:48.305Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>The Daoist quest for longevity and union with the Dao provides the spiritual backbone of Xianxia. Concepts like wu wei, internal alchemy, and the celestial bureaucracy all reappear, transformed, in fiction.</p>",
    "category": "Chinese Mythology",
    "cover": "https://images.hostinger.com/4087246a-2032-4fd3-8a66-7b61c27152ae.png",
    "created": "2026-07-26 04:38:48.305Z",
    "excerpt": "How Daoist philosophy and the pursuit of immortality shaped Xianxia.",
    "historical": "<p>Rooted in the Dao De Jing and Zhuangzi, Daoism developed elaborate practices for cultivating body and spirit over two millennia.</p>",
    "id": "8paartanu8e9072",
    "metaDescription": "Explore how Daoist philosophy and immortality practices shaped Xianxia cultivation stories.",
    "ogImage": "",
    "overview": "Daoism (道教) is the wellspring from which most cultivation imagery flows — from immortals and elixirs to the harmony of yin and yang.",
    "publishAt": "2026-07-26 04:38:48.000Z",
    "related": "neidan,qi,golden-core",
    "seoTitle": "Daoism in Cultivation Fiction | Spirit Root",
    "slug": "daoism",
    "status": "published",
    "tags": "daoism, philosophy, laozi, immortals",
    "title": "Daoism and Cultivation Fiction",
    "type": "wiki",
    "updated": "2026-07-26 04:38:48.305Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>Xianxia (仙侠) literally means 'immortal heroes'. It is a genre of Chinese fantasy centered on cultivators who train to transcend mortality, blending Daoist mysticism, martial arts, and epic adventure.</p><p>Unlike Western fantasy, its magic system is grounded in a coherent spiritual worldview of Qi, realms, and the Dao.</p>",
    "category": "Xianxia Culture",
    "cover": "https://images.hostinger.com/4706bfbe-2b15-4959-b4c3-154ee726fa1b.png",
    "created": "2026-07-26 04:38:48.305Z",
    "excerpt": "A short introduction to the genre of immortal-hero cultivation fiction.",
    "historical": "",
    "id": "jt23h92p736j8al",
    "metaDescription": "An introduction to Xianxia, the genre of Chinese cultivation and immortal-hero fiction.",
    "ogImage": "",
    "overview": "",
    "publishAt": "2026-07-26 04:38:48.000Z",
    "related": "",
    "seoTitle": "What is Xianxia? A Beginner's Guide | Spirit Root",
    "slug": "what-is-xianxia",
    "status": "published",
    "tags": "xianxia, genre, introduction",
    "title": "What is Xianxia?",
    "type": "blog",
    "updated": "2026-07-26 04:38:48.305Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>It is tempting to read Xianxia as a literal manual for enlightenment. But fictional cultivation compresses centuries of gradual inner work into dramatic breakthroughs and power levels.</p><p>Real Daoist and Buddhist practice is slower, quieter, and concerned less with power than with clarity, ethics, and letting go.</p>",
    "category": "Chinese Philosophy",
    "cover": "https://images.hostinger.com/073781d0-3ccf-4bfa-8c41-ea98ce86e8cd.png",
    "created": "2026-07-26 04:38:48.306Z",
    "excerpt": "Where the fantasy of cultivation ends and genuine practice begins.",
    "historical": "",
    "id": "oj35o8xp435h6gy",
    "metaDescription": "A reflection on the difference between Xianxia cultivation fantasy and genuine spiritual practice.",
    "ogImage": "",
    "overview": "",
    "publishAt": "2026-07-26 04:38:48.000Z",
    "related": "",
    "seoTitle": "Fictional Cultivation vs Real Spiritual Practice | Spirit Root",
    "slug": "fiction-vs-real-cultivation",
    "status": "published",
    "tags": "cultivation, daoism, reflection",
    "title": "Fictional Cultivation vs Real Spiritual Practice",
    "type": "blog",
    "updated": "2026-07-26 04:38:48.306Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>Fan translations, web-novel platforms, and animated adaptations turned Xianxia from a domestic genre into a global phenomenon. Its clear progression systems and rich mythology resonate with readers everywhere.</p>",
    "category": "Xianxia Culture",
    "cover": "https://images.hostinger.com/4087246a-2032-4fd3-8a66-7b61c27152ae.png",
    "created": "2026-07-26 04:38:48.306Z",
    "excerpt": "The web-novel boom that carried cultivation stories across the globe.",
    "historical": "",
    "id": "kuaoqfdp619jeqc",
    "metaDescription": "How web novels and translations made Xianxia cultivation fiction a global phenomenon.",
    "ogImage": "",
    "overview": "",
    "publishAt": "2026-07-26 04:38:48.000Z",
    "related": "",
    "seoTitle": "Why Xianxia Became Popular Worldwide | Spirit Root",
    "slug": "why-xianxia-popular",
    "status": "published",
    "tags": "xianxia, popularity, translation",
    "title": "Why Xianxia Became Popular Worldwide",
    "type": "blog",
    "updated": "2026-07-26 04:38:48.306Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>These are personal reflections rather than instruction. I write about my slow, imperfect attempts to sit quietly, follow the breath, and understand practices like Tiantai Zhiguan and Neidan.</p>",
    "category": "Meditation Practice",
    "cover": "https://images.hostinger.com/073781d0-3ccf-4bfa-8c41-ea98ce86e8cd.png",
    "created": "2026-07-26 04:38:48.306Z",
    "excerpt": "Personal notes on sitting with breath, stillness, and Chinese contemplative methods.",
    "historical": "",
    "id": "vdyer5rky4u5fy5",
    "metaDescription": "Personal reflections on exploring Chinese meditation traditions like Zhiguan and Neidan.",
    "ogImage": "",
    "overview": "",
    "publishAt": "2026-07-26 04:38:48.000Z",
    "related": "",
    "seoTitle": "My Journey Exploring Chinese Meditation | Spirit Root",
    "slug": "meditation-journey",
    "status": "published",
    "tags": "meditation, personal notes, zhiguan",
    "title": "My Journey Exploring Chinese Meditation Traditions",
    "type": "blog",
    "updated": "2026-07-26 04:38:48.306Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>本条目为占位资料，等待管理员填充详细内容。</p><p>建议包含：早期经历、修炼历程、重要战役、性格特征、重要法宝与功法等章节。</p>",
    "category": "人物",
    "cover": "",
    "created": "2026-08-10 11:51:09.299Z",
    "excerpt": "《凡人修仙传》男主角，出身平凡却凭借坚韧毅力与机缘一步步登顶修仙巅峰。",
    "historical": "",
    "id": "xfsdo9naup2li1t",
    "metaDescription": "《凡人修仙传》男主角，出身平凡却凭借坚韧毅力与机缘一步步登顶修仙巅峰。",
    "ogImage": "",
    "overview": "韩立（Han Li）是《凡人修仙传》的主人公。他出身平民，自幼入黄枫谷，以平凡灵根走上漫长修仙之路，历经数百年终成大乘修士。其成道之路以稳健著称，从不依赖天才资质，而靠积累、谋略与无数机缘。",
    "publishAt": "2026-08-10 11:51:09.000Z",
    "related": "wan-meng, cultivation-realms-fanren, qingyuan-sword-art",
    "seoTitle": "韩立 — 凡人修仙传 Wiki | Spirit Root",
    "slug": "han-li",
    "status": "published",
    "tags": "主角,韩立,平凡弟子,大乘期",
    "title": "韩立",
    "type": "wiki",
    "updated": "2026-08-10 11:51:09.299Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>本条目为占位资料，等待管理员填充详细内容。</p>",
    "category": "人物",
    "cover": "",
    "created": "2026-08-10 11:51:09.300Z",
    "excerpt": "韩立在人界的道侣，修为高洁，与韩立共历艰辛。",
    "historical": "",
    "id": "5k6jxcq2qd6dpyz",
    "metaDescription": "韩立在人界的道侣，修为高洁，与韩立共历艰辛。",
    "ogImage": "",
    "overview": "南宫婉是韩立在人界结识的挚友与道侣，曾被封于结界之中，后被韩立救出。",
    "publishAt": "2026-08-10 11:51:09.000Z",
    "related": "han-li",
    "seoTitle": "南宫婉 — 凡人修仙传 Wiki | Spirit Root",
    "slug": "nan-gong-wan",
    "status": "published",
    "tags": "女主角,南宫婉,元婴期,韩立",
    "title": "南宫婉",
    "type": "wiki",
    "updated": "2026-08-10 11:51:09.300Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>本条目为占位资料，等待管理员填充详细内容。</p>",
    "category": "人物",
    "cover": "",
    "created": "2026-08-10 11:51:09.300Z",
    "excerpt": "仙界重要人物，与韩立在仙界有深厚渊源。",
    "historical": "",
    "id": "luxue1shaa0dyq2",
    "metaDescription": "仙界重要人物，与韩立在仙界有深厚渊源。",
    "ogImage": "",
    "overview": "紫灵仙子是《凡人修仙传》仙界篇的重要角色。",
    "publishAt": "2026-08-10 11:51:09.000Z",
    "related": "han-li",
    "seoTitle": "紫灵仙子 — 凡人修仙传 Wiki | Spirit Root",
    "slug": "fairy-violet-spirit",
    "status": "published",
    "tags": "仙界,紫灵,韩立",
    "title": "紫灵仙子",
    "type": "wiki",
    "updated": "2026-08-10 11:51:09.300Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p><strong>人界境界（从低到高）：</strong></p><ul><li>炼气期（1–13层）</li><li>筑基期（初期、中期、后期）</li><li>结丹期（金丹期）</li><li>元婴期（初期、中期、后期）</li><li>化神期</li><li>合体期</li><li>大乘期</li><li>渡劫期</li></ul><p>仙界另有仙人、真仙等更高层次，本条目待管理员补充。</p>",
    "category": "境界体系",
    "cover": "",
    "created": "2026-08-10 11:51:09.300Z",
    "excerpt": "《凡人修仙传》中完整的修炼境界划分，从炼气期到大乘期乃至仙界的详细说明。",
    "historical": "",
    "id": "2tjqwv0cugop33y",
    "metaDescription": "《凡人修仙传》中完整的修炼境界划分，从炼气期到大乘期乃至仙界的详细说明。",
    "ogImage": "",
    "overview": "《凡人修仙传》建立了一套完整的修仙境界体系，人界分为：炼气期、筑基期、结丹期（金丹期）、元婴期、化神期、合体期、大乘期、渡劫期。每个大境界又细分若干小层次，每次突破都需要机缘与积累。",
    "publishAt": "2026-08-10 11:51:09.000Z",
    "related": "han-li, breakthrough-tribulation",
    "seoTitle": "修仙境界体系 — 凡人修仙传 Wiki | Spirit Root",
    "slug": "cultivation-realms-fanren",
    "status": "published",
    "tags": "境界,炼气,筑基,金丹,元婴,化神,合体,大乘,渡劫",
    "title": "修仙境界体系",
    "type": "wiki",
    "updated": "2026-08-10 11:51:09.300Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>本条目为占位资料，等待管理员填充详细内容。</p>",
    "category": "境界体系",
    "cover": "",
    "created": "2026-08-10 11:51:09.301Z",
    "excerpt": "修士突破大境界时面临天地劫难，稍有不慎便会身殒道消。",
    "historical": "",
    "id": "back7i459i7rzd2",
    "metaDescription": "修士突破大境界时面临天地劫难，稍有不慎便会身殒道消。",
    "ogImage": "",
    "overview": "修士在突破大境界，尤其是元婴期及以上时，必须承受天劫考验。天劫以雷劫最为常见，威力与修士境界成正比。",
    "publishAt": "2026-08-10 11:51:09.000Z",
    "related": "cultivation-realms-fanren",
    "seoTitle": "天劫与渡劫 — 凡人修仙传 Wiki | Spirit Root",
    "slug": "breakthrough-tribulation",
    "status": "published",
    "tags": "天劫,渡劫,雷劫,突破",
    "title": "天劫与渡劫",
    "type": "wiki",
    "updated": "2026-08-10 11:51:09.301Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>本条目为占位资料，等待管理员填充详细内容。</p>",
    "category": "功法秘术",
    "cover": "",
    "created": "2026-08-10 11:51:09.301Z",
    "excerpt": "韩立早期修炼的剑法功诀，奠定其飞剑体系的基础。",
    "historical": "",
    "id": "7r905qe6pkh9oe4",
    "metaDescription": "韩立早期修炼的剑法功诀，奠定其飞剑体系的基础。",
    "ogImage": "",
    "overview": "青元剑诀是韩立修炼飞剑之术的入门功法，后经不断完善演化为更高阶的剑道体系。",
    "publishAt": "2026-08-10 11:51:09.000Z",
    "related": "han-li, cultivation-realms-fanren",
    "seoTitle": "青元剑诀 — 凡人修仙传 Wiki | Spirit Root",
    "slug": "qingyuan-sword-art",
    "status": "published",
    "tags": "剑诀,青元,韩立,飞剑",
    "title": "青元剑诀",
    "type": "wiki",
    "updated": "2026-08-10 11:51:09.301Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>本条目为占位资料，等待管理员填充详细内容。</p>",
    "category": "功法秘术",
    "cover": "",
    "created": "2026-08-10 11:51:09.301Z",
    "excerpt": "韩立修炼的强大神通之一，蕴含深厚的道法变化。",
    "historical": "",
    "id": "kyt9rzuzakt6dnj",
    "metaDescription": "韩立修炼的强大神通之一，蕴含深厚的道法变化。",
    "ogImage": "",
    "overview": "大衍神通是《凡人修仙传》中韩立掌握的重要神通，以变化莫测著称。",
    "publishAt": "2026-08-10 11:51:09.000Z",
    "related": "han-li",
    "seoTitle": "大衍神通 — 凡人修仙传 Wiki | Spirit Root",
    "slug": "great-development-technique",
    "status": "published",
    "tags": "神通,大衍,韩立",
    "title": "大衍神通",
    "type": "wiki",
    "updated": "2026-08-10 11:51:09.301Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>本条目为占位资料，等待管理员填充详细内容。</p>",
    "category": "功法秘术",
    "cover": "",
    "created": "2026-08-10 11:51:09.302Z",
    "excerpt": "融合魔道精髓的高阶功法，威力极大却需慎重修炼。",
    "historical": "",
    "id": "0ldgs1x940s7bzr",
    "metaDescription": "融合魔道精髓的高阶功法，威力极大却需慎重修炼。",
    "ogImage": "",
    "overview": "真魔功是韩立后期修炼的重要功法之一，融合了魔界精髓，大幅提升战斗力。",
    "publishAt": "2026-08-10 11:51:09.000Z",
    "related": "han-li, cultivation-realms-fanren",
    "seoTitle": "真魔功 — 凡人修仙传 Wiki | Spirit Root",
    "slug": "provenance-true-devil-art",
    "status": "published",
    "tags": "魔功,真魔,韩立,魔道",
    "title": "真魔功",
    "type": "wiki",
    "updated": "2026-08-10 11:51:09.302Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>本条目为占位资料，等待管理员填充详细内容。</p>",
    "category": "法宝",
    "cover": "",
    "created": "2026-08-10 11:51:09.302Z",
    "excerpt": "韩立标志性的攻击法宝，七十二把竹蜂云剑齐出威力惊人。",
    "historical": "",
    "id": "4m2audrmnbt5565",
    "metaDescription": "韩立标志性的攻击法宝，七十二把竹蜂云剑齐出威力惊人。",
    "ogImage": "",
    "overview": "韩立以竹蜂云剑为核心，凝练出七十二路飞剑阵法，是其招牌战术之一。",
    "publishAt": "2026-08-10 11:51:09.000Z",
    "related": "han-li, qingyuan-sword-art",
    "seoTitle": "七十二路飞剑 — 凡人修仙传 Wiki | Spirit Root",
    "slug": "seventy-two-flying-swords",
    "status": "published",
    "tags": "飞剑,法宝,韩立,竹灵剑",
    "title": "七十二路飞剑",
    "type": "wiki",
    "updated": "2026-08-10 11:51:09.302Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>本条目为占位资料，等待管理员填充详细内容。</p>",
    "category": "法宝",
    "cover": "",
    "created": "2026-08-10 11:51:09.302Z",
    "excerpt": "修仙界中极为珍稀的天地异火，对炼器与战斗均有重要价值。",
    "historical": "",
    "id": "80mi9m2j0w2rdvw",
    "metaDescription": "修仙界中极为珍稀的天地异火，对炼器与战斗均有重要价值。",
    "ogImage": "",
    "overview": "天地灵火是《凡人修仙传》中出现的各类珍稀异火的统称，韩立曾收集多种用于炼器与战斗。",
    "publishAt": "2026-08-10 11:51:09.000Z",
    "related": "han-li",
    "seoTitle": "天地灵火 — 凡人修仙传 Wiki | Spirit Root",
    "slug": "heaven-earth-spirit-flame",
    "status": "published",
    "tags": "灵火,炼器,韩立",
    "title": "天地灵火",
    "type": "wiki",
    "updated": "2026-08-10 11:51:09.302Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>本条目为占位资料，等待管理员填充详细内容。</p>",
    "category": "宗门势力",
    "cover": "",
    "created": "2026-08-10 11:51:09.302Z",
    "excerpt": "天南修仙界的重要宗门之一，韩立曾在此留下深刻印记。",
    "historical": "",
    "id": "63eaj9nuk7ukogt",
    "metaDescription": "天南修仙界的重要宗门之一，韩立曾在此留下深刻印记。",
    "ogImage": "",
    "overview": "落云宗是天南修仙界的顶级势力之一，门规严格，弟子众多。韩立与落云宗的渊源贯穿了其在天南的早中期岁月。",
    "publishAt": "2026-08-10 11:51:09.000Z",
    "related": "han-li",
    "seoTitle": "落云宗 — 凡人修仙传 Wiki | Spirit Root",
    "slug": "luoyun-sect",
    "status": "published",
    "tags": "宗门,落云宗,人界",
    "title": "落云宗",
    "type": "wiki",
    "updated": "2026-08-10 11:51:09.302Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>本条目为占位资料，等待管理员填充详细内容。</p>",
    "category": "宗门势力",
    "cover": "",
    "created": "2026-08-10 11:51:09.303Z",
    "excerpt": "天南人界中由多国修仙门派组成的联合势力，与魔道长期对峙。",
    "historical": "",
    "id": "fy0tb4pt35re9j3",
    "metaDescription": "天南人界中由多国修仙门派组成的联合势力，与魔道长期对峙。",
    "ogImage": "",
    "overview": "九国联盟是天南人界修仙界的重要政治结构，由正道门派与世俗国家联合组成，对抗魔道势力。",
    "publishAt": "2026-08-10 11:51:09.000Z",
    "related": "luoyun-sect",
    "seoTitle": "九国联盟 — 凡人修仙传 Wiki | Spirit Root",
    "slug": "nine-kingdoms-alliance",
    "status": "published",
    "tags": "九国,联盟,人界,战争",
    "title": "九国联盟",
    "type": "wiki",
    "updated": "2026-08-10 11:51:09.303Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>本条目为占位资料，等待管理员填充详细内容。</p>",
    "category": "灵兽",
    "cover": "",
    "created": "2026-08-10 11:51:09.315Z",
    "excerpt": "韩立豢养的奇特灵兽，以吞噬鬼魂为食，外形憨厚内里却威力强大。",
    "historical": "",
    "id": "jb28f0dq4n02zv8",
    "metaDescription": "韩立豢养的奇特灵兽，以吞噬鬼魂为食，外形憨厚内里却威力强大。",
    "ogImage": "",
    "overview": "噬魂兽（Weeping Soul Beast）是韩立早期获得的灵兽，外形似熊，能吞噬鬼魂，在战斗中出奇制胜。",
    "publishAt": "2026-08-10 11:51:09.000Z",
    "related": "han-li",
    "seoTitle": "噬魂兽 — 凡人修仙传 Wiki | Spirit Root",
    "slug": "weeping-soul-beast",
    "status": "published",
    "tags": "灵兽,噬魂兽,韩立,吞噬",
    "title": "噬魂兽",
    "type": "wiki",
    "updated": "2026-08-10 11:51:09.315Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>本条目为占位资料，等待管理员填充详细内容。</p>",
    "category": "灵兽",
    "cover": "",
    "created": "2026-08-10 11:51:09.316Z",
    "excerpt": "韩立后期的强力灵兽，兼具速度与战力，忠诚可靠。",
    "historical": "",
    "id": "9xy8z8kwo7jm6tl",
    "metaDescription": "韩立后期的强力灵兽，兼具速度与战力，忠诚可靠。",
    "ogImage": "",
    "overview": "豹麟兽是韩立修仙后期豢养的重要灵兽，速度与攻击力均十分出色。",
    "publishAt": "2026-08-10 11:51:09.000Z",
    "related": "han-li",
    "seoTitle": "豹麟兽 — 凡人修仙传 Wiki | Spirit Root",
    "slug": "leopard-kirin-beast",
    "status": "published",
    "tags": "灵兽,豹麟,韩立,坐骑",
    "title": "豹麟兽",
    "type": "wiki",
    "updated": "2026-08-10 11:51:09.316Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>本条目为占位资料，等待管理员填充详细内容。</p><p>建议包含：地域划分、重要宗门分布、主要秘境等内容。</p>",
    "category": "地图",
    "cover": "",
    "created": "2026-08-10 11:51:09.316Z",
    "excerpt": "韩立修仙初期长期活动的地域，分布众多宗门与秘境。",
    "historical": "",
    "id": "0s8onpu0ungo132",
    "metaDescription": "韩立修仙初期长期活动的地域，分布众多宗门与秘境。",
    "ogImage": "",
    "overview": "天南修仙界是韩立度过漫长修仙初期的主要舞台，地域辽阔，宗门林立，秘境众多，是《凡人修仙传》人界篇的核心地图。",
    "publishAt": "2026-08-10 11:51:09.000Z",
    "related": "luoyun-sect, nine-kingdoms-alliance",
    "seoTitle": "天南修仙界 — 凡人修仙传 Wiki | Spirit Root",
    "slug": "tiannan-region",
    "status": "published",
    "tags": "天南,地图,人界,修仙",
    "title": "天南修仙界",
    "type": "wiki",
    "updated": "2026-08-10 11:51:09.316Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>本条目为占位资料，等待管理员填充详细内容。</p>",
    "category": "地图",
    "cover": "",
    "created": "2026-08-10 11:51:09.316Z",
    "excerpt": "凌驾于人界之上的更高层次世界，修士渡劫成功后可飞升至此。",
    "historical": "",
    "id": "q9tgzvi08v1jl5f",
    "metaDescription": "凌驾于人界之上的更高层次世界，修士渡劫成功后可飞升至此。",
    "ogImage": "",
    "overview": "灵界是《凡人修仙传》中人界之上的大千世界，资源更为丰富，强者如云，韩立飞升后的主要活动舞台。",
    "publishAt": "2026-08-10 11:51:09.000Z",
    "related": "cultivation-realms-fanren, han-li",
    "seoTitle": "灵界 — 凡人修仙传 Wiki | Spirit Root",
    "slug": "spirit-realm",
    "status": "published",
    "tags": "灵界,上界,天界,修仙",
    "title": "灵界",
    "type": "wiki",
    "updated": "2026-08-10 11:51:09.316Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>本条目为占位资料，等待管理员填充详细内容。</p><p>建议按章节或时期划分，逐条列出关键事件。</p>",
    "category": "剧情时间线",
    "cover": "",
    "created": "2026-08-10 11:51:09.316Z",
    "excerpt": "韩立从炼气期到渡劫飞升的漫长人界历程中的重要事件梳理。",
    "historical": "",
    "id": "ptcglyejazgaco3",
    "metaDescription": "韩立从炼气期到渡劫飞升的漫长人界历程中的重要事件梳理。",
    "ogImage": "",
    "overview": "本条目梳理韩立在人界期间（炼气至渡劫）的重要事件节点，帮助读者快速回顾剧情脉络。",
    "publishAt": "2026-08-10 11:51:09.000Z",
    "related": "han-li, cultivation-realms-fanren",
    "seoTitle": "人界篇时间线 — 凡人修仙传 Wiki | Spirit Root",
    "slug": "plot-timeline-mortal-world",
    "status": "published",
    "tags": "时间线,人界,剧情,事件",
    "title": "人界篇时间线",
    "type": "wiki",
    "updated": "2026-08-10 11:51:09.316Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>本条目为占位资料，等待管理员填充详细内容。</p>",
    "category": "剧情时间线",
    "cover": "",
    "created": "2026-08-10 11:51:09.317Z",
    "excerpt": "韩立飞升灵界后的重要剧情事件与势力交锋梳理。",
    "historical": "",
    "id": "mco62tuc0kobt2x",
    "metaDescription": "韩立飞升灵界后的重要剧情事件与势力交锋梳理。",
    "ogImage": "",
    "overview": "本条目梳理韩立在灵界（飞升后至大乘期）的重要事件节点与势力变化。",
    "publishAt": "2026-08-10 11:51:09.000Z",
    "related": "han-li, spirit-realm",
    "seoTitle": "灵界篇时间线 — 凡人修仙传 Wiki | Spirit Root",
    "slug": "plot-timeline-spirit-realm",
    "status": "published",
    "tags": "时间线,灵界,剧情,事件",
    "title": "灵界篇时间线",
    "type": "wiki",
    "updated": "2026-08-10 11:51:09.317Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>灵根类型：</p><ul><li><strong>单灵根</strong>：五系其一，最为纯净，天才资质</li><li><strong>双灵根</strong>：含两种属性，仍属优秀</li><li><strong>三灵根</strong>：中等资质</li><li><strong>四灵根</strong>：资质较差</li><li><strong>五灵根</strong>：俗称废灵根，修炼艰难</li><li><strong>变异灵根</strong>：特殊属性，可能是福也可能是祸</li></ul>",
    "category": "名词索引",
    "cover": "",
    "created": "2026-08-10 11:51:09.317Z",
    "excerpt": "修仙者的先天资质，决定其修炼速度与上限，分单灵根至五灵根等多种类型。",
    "historical": "",
    "id": "vh8n6pjyowcmtux",
    "metaDescription": "修仙者的先天资质，决定其修炼速度与上限，分单灵根至五灵根等多种类型。",
    "ogImage": "",
    "overview": "灵根是《凡人修仙传》中修仙者先天修炼资质的核心概念，分单灵根（最佳）至五灵根（最差）。灵根属性与金、木、水、火、土五行对应。灵根越纯，修炼越快，突破越容易。",
    "publishAt": "2026-08-10 11:51:09.000Z",
    "related": "cultivation-realms-fanren",
    "seoTitle": "灵根 — 凡人修仙传 Wiki | Spirit Root",
    "slug": "glossary-linggen",
    "status": "published",
    "tags": "灵根,资质,修仙基础",
    "title": "灵根",
    "type": "wiki",
    "updated": "2026-08-10 11:51:09.317Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>本条目为占位资料，等待管理员填充详细内容。</p>",
    "category": "名词索引",
    "cover": "",
    "created": "2026-08-10 11:51:09.317Z",
    "excerpt": "炼制丹药所需的配方，是修仙界珍贵资源的重要来源。",
    "historical": "",
    "id": "quj90pk4qipsc2d",
    "metaDescription": "炼制丹药所需的配方，是修仙界珍贵资源的重要来源。",
    "ogImage": "",
    "overview": "丹方是炼制修仙丹药的配方，记录所需药材、配比、火候等要素，品阶越高的丹方越为稀缺。",
    "publishAt": "2026-08-10 11:51:09.000Z",
    "related": "cultivation-realms-fanren",
    "seoTitle": "丹方 — 凡人修仙传 Wiki | Spirit Root",
    "slug": "glossary-dan-fang",
    "status": "published",
    "tags": "丹药,炼丹,配方,名词",
    "title": "丹方",
    "type": "wiki",
    "updated": "2026-08-10 11:51:09.317Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>大致品阶划分（由低至高）：</p><ul><li>法器（低/中/高阶）</li><li>灵宝（低/中/高阶）</li><li>仙器（下品/中品/上品）</li></ul><p>具体细分与各阶特征待管理员补充。</p>",
    "category": "名词索引",
    "cover": "",
    "created": "2026-08-10 11:51:09.318Z",
    "excerpt": "《凡人修仙传》中法宝按品阶划分的体系说明，从低阶法器到仙器逐级递增。",
    "historical": "",
    "id": "zshf8ll62v0a36y",
    "metaDescription": "《凡人修仙传》中法宝按品阶划分的体系说明，从低阶法器到仙器逐级递增。",
    "ogImage": "",
    "overview": "法宝品阶体系是修仙界衡量法宝价值的标准，大致分为：法器、灵宝、仙器等层次，每类又有品级之分。",
    "publishAt": "2026-08-10 11:51:09.000Z",
    "related": "seventy-two-flying-swords, heaven-earth-spirit-flame",
    "seoTitle": "法宝品阶 — 凡人修仙传 Wiki | Spirit Root",
    "slug": "glossary-magic-treasure-grades",
    "status": "published",
    "tags": "法宝,品阶,灵宝,仙器,名词",
    "title": "法宝品阶",
    "type": "wiki",
    "updated": "2026-08-10 11:51:09.318Z",
    "author": "",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<h2>止与观的含义</h2><p>（待补充：本节将围绕「止与观的含义」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>为何强调双运</h2><p>（待补充：本节将围绕「为何强调双运」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>入门练习次第</h2><p>（待补充：本节将围绕「入门练习次第」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>常见误区</h2><p>（待补充：本节将围绕「常见误区」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>延伸思考</h2><p>（待补充：本节将围绕「延伸思考」展开原创概述与整理，内容由管理员逐步填充。）</p>",
    "category": "止观",
    "cover": "",
    "created": "2026-08-13 06:18:08.498Z",
    "excerpt": "清凉月老师对止观双运的概括性介绍，强调止与观并行而非先后，是禅修入门的核心框架。",
    "historical": "",
    "id": "ku571g165ltj3yi",
    "metaDescription": "清凉月老师对止观双运的概括性介绍，强调止与观并行而非先后，是禅修入门的核心框架。",
    "ogImage": "",
    "overview": "本文为清凉月老师关于止观双运的原创概述。止（奢摩他）令心安定，观（毗钵舍那）令心明了，二者双运是禅修入门的关键。文章以概括性语言梳理其教学要点，供读者建立基本认识。",
    "publishAt": "2026-08-13 06:18:08.000Z",
    "related": "qingliangyue-daily-awareness,qingliangyue-breath-mind",
    "seoTitle": "止观双运的入门要点 — 修行人著述 | Spirit Root",
    "slug": "qingliangyue-zhiguan-intro",
    "status": "published",
    "tags": "止观,禅修,入门,清凉月",
    "title": "止观双运的入门要点",
    "type": "wiki",
    "updated": "2026-08-13 06:18:08.498Z",
    "author": "qingliangyue",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<h2>什么是觉照</h2><p>（待补充：本节将围绕「什么是觉照」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>座下与座上的衔接</h2><p>（待补充：本节将围绕「座下与座上的衔接」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>具体场景的练习</h2><p>（待补充：本节将围绕「具体场景的练习」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>容易中断的原因</h2><p>（待补充：本节将围绕「容易中断的原因」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>小结</h2><p>（待补充：本节将围绕「小结」展开原创概述与整理，内容由管理员逐步填充。）</p>",
    "category": "觉照",
    "cover": "",
    "created": "2026-08-13 06:18:08.498Z",
    "excerpt": "如何在行住坐卧中保持觉照，是清凉月老师教学中最贴近生活的部分。",
    "historical": "",
    "id": "q8pmz2nb2ies2us",
    "metaDescription": "如何在行住坐卧中保持觉照，是清凉月老师教学中最贴近生活的部分。",
    "ogImage": "",
    "overview": "本文概述清凉月老师关于日常觉照的教导：修行不必局限于座上，行住坐卧皆可练习觉照。文章以概括性结构呈现其要点，留出空白章节待补充实例与体会。",
    "publishAt": "2026-08-13 06:18:08.000Z",
    "related": "qingliangyue-zhiguan-intro,qingliangyue-breath-mind",
    "seoTitle": "日常生活中的觉照 — 修行人著述 | Spirit Root",
    "slug": "qingliangyue-daily-awareness",
    "status": "published",
    "tags": "觉照,日常,正念,清凉月",
    "title": "日常生活中的觉照",
    "type": "wiki",
    "updated": "2026-08-13 06:18:08.498Z",
    "author": "qingliangyue",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<h2>呼吸作为观察窗口</h2><p>（待补充：本节将围绕「呼吸作为观察窗口」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>数息与随息</h2><p>（待补充：本节将围绕「数息与随息」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>粗细与深浅</h2><p>（待补充：本节将围绕「粗细与深浅」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>心息相依的体会</h2><p>（待补充：本节将围绕「心息相依的体会」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>注意事项</h2><p>（待补充：本节将围绕「注意事项」展开原创概述与整理，内容由管理员逐步填充。）</p>",
    "category": "禅修",
    "cover": "",
    "created": "2026-08-13 06:18:08.499Z",
    "excerpt": "清凉月老师从呼吸入手讲解心念的调伏，指出呼吸是观察心的便捷窗口。",
    "historical": "",
    "id": "wosqj4e65lvblve",
    "metaDescription": "清凉月老师从呼吸入手讲解心念的调伏，指出呼吸是观察心的便捷窗口。",
    "ogImage": "",
    "overview": "本文概括清凉月老师关于呼吸与心念关系的讲解：呼吸粗细反映心的状态，借由数息、随息可令心渐趋安定。文章以原创概述为主，保留空白结构以便后续整理。",
    "publishAt": "2026-08-13 06:18:08.000Z",
    "related": "qingliangyue-zhiguan-intro,qingliangyue-daily-awareness",
    "seoTitle": "呼吸与心念的关联 — 修行人著述 | Spirit Root",
    "slug": "qingliangyue-breath-mind",
    "status": "published",
    "tags": "呼吸,心念,数息,清凉月",
    "title": "呼吸与心念的关联",
    "type": "wiki",
    "updated": "2026-08-13 06:18:08.499Z",
    "author": "qingliangyue",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<h2>本净与客尘</h2><p>（待补充：本节将围绕「本净与客尘」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>认识心性的途径</h2><p>（待补充：本节将围绕「认识心性的途径」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>理悟与证悟的差别</h2><p>（待补充：本节将围绕「理悟与证悟的差别」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>常见疑问</h2><p>（待补充：本节将围绕「常见疑问」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>延伸阅读</h2><p>（待补充：本节将围绕「延伸阅读」展开原创概述与整理，内容由管理员逐步填充。）</p>",
    "category": "心性",
    "cover": "",
    "created": "2026-08-13 06:18:08.499Z",
    "excerpt": "杨宁老师对「心性本净」的概括讲解，指出烦恼客尘并不改变心的本性。",
    "historical": "",
    "id": "6ne38crxj1cv54b",
    "metaDescription": "杨宁老师对「心性本净」的概括讲解，指出烦恼客尘并不改变心的本性。",
    "ogImage": "",
    "overview": "本文概述杨宁老师关于心性本净的教导：心之本性本自清净，烦恼如客尘暂现而不染本体。文章以原创概括性语言呈现其教学要点，并保留空白章节待充实。",
    "publishAt": "2026-08-13 06:18:08.000Z",
    "related": "yangning-scripture-practice,yangning-affliction-bodhi",
    "seoTitle": "心性本净的含义 — 修行人著述 | Spirit Root",
    "slug": "yangning-nature-of-mind",
    "status": "published",
    "tags": "心性,本净,佛性,杨宁",
    "title": "心性本净的含义",
    "type": "wiki",
    "updated": "2026-08-13 06:18:08.499Z",
    "author": "yangning",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<h2>读经的目的</h2><p>（待补充：本节将围绕「读经的目的」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>概念与实证的差距</h2><p>（待补充：本节将围绕「概念与实证的差距」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>如何以经印心</h2><p>（待补充：本节将围绕「如何以经印心」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>选择适合的经典</h2><p>（待补充：本节将围绕「选择适合的经典」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>小结</h2><p>（待补充：本节将围绕「小结」展开原创概述与整理，内容由管理员逐步填充。）</p>",
    "category": "经典",
    "cover": "",
    "created": "2026-08-13 06:18:08.499Z",
    "excerpt": "杨宁老师强调读经须与实修相应，否则易停留在概念层面。",
    "historical": "",
    "id": "vbl1avyb8vkvt5s",
    "metaDescription": "杨宁老师强调读经须与实修相应，否则易停留在概念层面。",
    "ogImage": "",
    "overview": "本文概括杨宁老师关于经典与实修结合的教导：经典是指月之指，研读须落于身心实证。文章以原创概述梳理其要点，留出空白结构以便补充具体经文与体会。",
    "publishAt": "2026-08-13 06:18:08.000Z",
    "related": "yangning-nature-of-mind,yangning-affliction-bodhi",
    "seoTitle": "经典研读与实修的结合 — 修行人著述 | Spirit Root",
    "slug": "yangning-scripture-practice",
    "status": "published",
    "tags": "经典,实修,教理,杨宁",
    "title": "经典研读与实修的结合",
    "type": "wiki",
    "updated": "2026-08-13 06:18:08.499Z",
    "author": "yangning",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<h2>烦恼与菩提的关系</h2><p>（待补充：本节将围绕「烦恼与菩提的关系」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>转烦恼为道用</h2><p>（待补充：本节将围绕「转烦恼为道用」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>觉与不觉的分野</h2><p>（待补充：本节将围绕「觉与不觉的分野」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>实践中的体会</h2><p>（待补充：本节将围绕「实践中的体会」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>延伸思考</h2><p>（待补充：本节将围绕「延伸思考」展开原创概述与整理，内容由管理员逐步填充。）</p>",
    "category": "心性",
    "cover": "",
    "created": "2026-08-13 06:18:08.499Z",
    "excerpt": "杨宁老师对「烦恼即菩提」的概括性解读，强调转而非断。",
    "historical": "",
    "id": "9qo4pt0wkaytbq5",
    "metaDescription": "杨宁老师对「烦恼即菩提」的概括性解读，强调转而非断。",
    "ogImage": "",
    "overview": "本文概述杨宁老师对「烦恼即菩提」的讲解：烦恼之性即菩提，关键在于觉与不觉，而非强行断除。文章以原创概括语言呈现，保留空白章节待整理实例。",
    "publishAt": "2026-08-13 06:18:08.000Z",
    "related": "yangning-nature-of-mind,yangning-scripture-practice",
    "seoTitle": "烦恼即菩提的理解 — 修行人著述 | Spirit Root",
    "slug": "yangning-affliction-bodhi",
    "status": "published",
    "tags": "烦恼,菩提,转依,杨宁",
    "title": "烦恼即菩提的理解",
    "type": "wiki",
    "updated": "2026-08-13 06:18:08.499Z",
    "author": "yangning",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<h2>缘起</h2><p>（待补充：本节将围绕「缘起」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>近期打坐的粗略情况</h2><p>（待补充：本节将围绕「近期打坐的粗略情况」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>一点小体会</h2><p>（待补充：本节将围绕「一点小体会」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>遇到的困难</h2><p>（待补充：本节将围绕「遇到的困难」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>自勉</h2><p>（待补充：本节将围绕「自勉」展开原创概述与整理，内容由管理员逐步填充。）</p>",
    "category": "日记",
    "cover": "",
    "created": "2026-08-13 06:18:08.500Z",
    "excerpt": "豆腐块以朴素文字记录日常打坐的点滴，风格平实亲切。",
    "historical": "",
    "id": "omyt1mi0ps3n0om",
    "metaDescription": "豆腐块以朴素文字记录日常打坐的点滴，风格平实亲切。",
    "ogImage": "",
    "overview": "本文为豆腐块的打坐日记类文章，以原创概括性记录日常打坐的粗浅体会，不涉及具体传承教法。文章保留空白结构，待作者逐步补充真实记录。",
    "publishAt": "2026-08-13 06:18:08.000Z",
    "related": "doufukuai-tofu-insight,doufukuai-ordinary-practice",
    "seoTitle": "我的打坐日记 — 修行人著述 | Spirit Root",
    "slug": "doufukuai-meditation-diary",
    "status": "published",
    "tags": "打坐,日记,体悟,豆腐块",
    "title": "我的打坐日记",
    "type": "wiki",
    "updated": "2026-08-13 06:18:08.500Z",
    "author": "doufukuai",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<h2>豆腐的朴素</h2><p>（待补充：本节将围绕「豆腐的朴素」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>由物及心的联想</h2><p>（待补充：本节将围绕「由物及心的联想」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>对修行的提醒</h2><p>（待补充：本节将围绕「对修行的提醒」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>一点自嘲</h2><p>（待补充：本节将围绕「一点自嘲」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>结语</h2><p>（待补充：本节将围绕「结语」展开原创概述与整理，内容由管理员逐步填充。）</p>",
    "category": "随笔",
    "cover": "",
    "created": "2026-08-13 06:18:08.500Z",
    "excerpt": "从一块朴素的豆腐中，豆腐块体会到修行应有的平实与无华。",
    "historical": "",
    "id": "hokh8xexyzdfk5a",
    "metaDescription": "从一块朴素的豆腐中，豆腐块体会到修行应有的平实与无华。",
    "ogImage": "",
    "overview": "本文为豆腐块的随笔，以一块豆腐为喻，抒发对平实修行的原创感悟。文章以概括性语言起笔，保留空白章节以便延展具体联想与体会。",
    "publishAt": "2026-08-13 06:18:08.000Z",
    "related": "doufukuai-meditation-diary,doufukuai-ordinary-practice",
    "seoTitle": "一块豆腐的启示 — 修行人著述 | Spirit Root",
    "slug": "doufukuai-tofu-insight",
    "status": "published",
    "tags": "豆腐,随笔,平凡,豆腐块",
    "title": "一块豆腐的启示",
    "type": "wiki",
    "updated": "2026-08-13 06:18:08.500Z",
    "author": "doufukuai",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<h2>在家修行的难处</h2><p>（待补充：本节将围绕「在家修行的难处」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>于日常中用心</h2><p>（待补充：本节将围绕「于日常中用心」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>家庭与修行的平衡</h2><p>（待补充：本节将围绕「家庭与修行的平衡」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>一点小小的坚持</h2><p>（待补充：本节将围绕「一点小小的坚持」展开原创概述与整理，内容由管理员逐步填充。）</p><h2>结语</h2><p>（待补充：本节将围绕「结语」展开原创概述与整理，内容由管理员逐步填充。）</p>",
    "category": "随笔",
    "cover": "",
    "created": "2026-08-13 06:18:08.500Z",
    "excerpt": "豆腐块记录在家人如何在平凡生活中安顿身心、随缘修行。",
    "historical": "",
    "id": "drm71bh33leick4",
    "metaDescription": "豆腐块记录在家人如何在平凡生活中安顿身心、随缘修行。",
    "ogImage": "",
    "overview": "本文概述豆腐块作为在家人于平凡生活中修行的体会：不必远求，于柴米油盐间亦可用心。文章以原创概括语言呈现，保留空白结构待补充生活片段。",
    "publishAt": "2026-08-13 06:18:08.000Z",
    "related": "doufukuai-meditation-diary,doufukuai-tofu-insight",
    "seoTitle": "平凡日子里的修行 — 修行人著述 | Spirit Root",
    "slug": "doufukuai-ordinary-practice",
    "status": "published",
    "tags": "平凡,生活,在家人,豆腐块",
    "title": "平凡日子里的修行",
    "type": "wiki",
    "updated": "2026-08-13 06:18:08.500Z",
    "author": "doufukuai",
    "titleEn": "",
    "categoryEn": "",
    "tagsEn": "",
    "excerptEn": "",
    "overviewEn": "",
    "bodyEn": "",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>禅宗是什么？什么是破初参和大彻大悟？禅宗的修行步骤是什么？</p><p>有的人总是觉得这个禅宗是个稀奇古怪的东西，好像神秘得不得了，其实它没什么神秘的，和观青色青光原理完全是一样的，就是通过相应的方法进行。因为我们当前这种状态也是由如来藏生成的，如来藏的所有的特征，我们当前这种状态都有，你与诸佛一点不差，诸佛有的东西，你也有，你与诸佛错在哪里？就错在人家那个状态，特征，全部都能够展现出来，能够恒定的、稳定的、深刻地展现出来，你不能，唯一的就错在这个地方。</p><p>所以一定要掌握这一点，要不然人家告诉你，你本来就是佛，哎呀我不是佛，你一点都不敢承认的。</p><p>禅宗就是告诉你当前这种状态，哪些特征是如来藏展现出来的，就是古人说的“六根门头，放光动地”，哪些特征是如来藏展现出来的，然后你去安住于这个特征，让时间延续。</p><p>所以第一步就是，人家告诉你，哪些特征是如来藏展现出来的，你经过这样的点，点，点，你终于知道，哦，原来这些特征是如来藏展现出来的，这叫什么？这叫明心，破初参，第一关你过了，你知道该怎样用功了，心该怎样用了，修行该怎样用功了，这仅仅只是第一关。</p><p>第二关你在干什么？你就必须唯一的安住于这个特征，然后通过这个特征，你回归如来藏，这才是真正的大彻大悟了，只有回归如来藏才大彻大悟，前面的那个仅仅只是明心而已，后面的才回归如来藏，咱们说明心见性，这一关过了之后，叫做完成了一个思维的回归，也就我们证入了如来藏。</p><p>思维方面解决了，但物质方面的应用你还没有真正掌握，于是还有最后一步，你要完成物质方面应用，就是证入八地，最后一个叫百尺竿头，更进一步，没有最后这一步也是不行的，也是你成功不了的，也就是说禅宗的修行，这三步也是按照这样的原理去进行。</p><p>那么这三步你也看得出，和佛教的一般的修行都是一样的，都是先证入初地，先证入回归如来藏，然后再证入八地，证得意生身，获得一个物质的自由，这就是我们的实证最基本的原理，一定要掌握，掌握这个原理之后，你就知道该怎么做了。</p>",
    "category": "禅宗",
    "cover": "",
    "created": "2026-08-13 08:27:00.491Z",
    "excerpt": "清凉月老师对禅宗修行次第的概括讲解：从明心破初参，到回归如来藏的大彻大悟，再到证入八地的物质自在，三步原理清晰可循。",
    "historical": "",
    "id": "2bu3blxvh9y1izr",
    "metaDescription": "A summary by Qingliangyue of the Chan path of practice: from clarifying the mind and breaking the first barrier, to the great awakening of returning to the Tathāgatagarbha, and finally to the freedom of matter at the eighth stage — three steps with a clear underlying principle.",
    "ogImage": "",
    "overview": "本文为清凉月老师关于禅宗实证步骤的原创概述。禅宗并非神秘莫测，其原理与观青色青光一致：当前状态本由如来藏生成，如来藏的一切特征当前状态皆有，差别只在于能否恒定、稳定、深刻地展现。文章梳理明心破初参、回归如来藏的大彻大悟、以及证入八地得物质自在这三步，并指出其与佛教一般修行次第相通。",
    "publishAt": "2026-08-13 08:27:00.000Z",
    "related": "qingliangyue-zhiguan-intro,qingliangyue-breath-mind",
    "seoTitle": "The Empirical Steps of Chan Buddhism — Practitioner Writings | Spirit Root",
    "slug": "qingliangyue-chan-steps",
    "status": "published",
    "tags": "禅宗,实证,明心见性,如来藏,清凉月",
    "title": "禅宗的实证步骤",
    "type": "wiki",
    "updated": "2026-08-13 08:27:00.491Z",
    "author": "qingliangyue",
    "titleEn": "The Empirical Steps of Chan Buddhism",
    "categoryEn": "Chan Buddhism",
    "tagsEn": "Chan,Empirical Practice,Seeing Nature,Tathāgatagarbha,Qingliangyue",
    "excerptEn": "A summary by Qingliangyue of the Chan path of practice: from clarifying the mind and breaking the first barrier, to the great awakening of returning to the Tathāgatagarbha, and finally to the freedom of matter at the eighth stage — three steps with a clear underlying principle.",
    "overviewEn": "This is an original overview by Qingliangyue on the empirical steps of Chan. Chan is not mysterious; its principle is the same as contemplating blue light: our present state is generated by the Tathāgatagarbha, and every feature of the Tathāgatagarbha is already present here — the only difference is whether those features can manifest constantly, stably, and deeply. The article outlines three steps — clarifying the mind and breaking the first barrier, the great awakening of returning to the Tathāgatagarbha, and attaining freedom of matter at the eighth stage — and notes their correspondence with the general Buddhist path.",
    "bodyEn": "<p>What is Chan? What does it mean to break the first barrier and to attain great awakening? What are the steps of Chan practice?</p><p>Some people always feel that Chan is something bizarre and impossibly mysterious. In fact it is not mysterious at all — its principle is exactly the same as contemplating blue light: one proceeds by means of a corresponding method. Because our present state is also generated by the Tathāgatagarbha, every feature of the Tathāgatagarbha is already present in our current state. You are no different from the Buddhas: what the Buddhas have, you also have. Where do you differ from them? Only in that, in their state, all the features can manifest — constantly, stably, and deeply — whereas you cannot. That is the sole difference.</p><p>So you must grasp this point; otherwise, when someone tells you that you are already a Buddha, you will say, \"Oh, I am not a Buddha,\" and not dare to acknowledge it at all.</p><p>Chan simply tells you which features of your current state are manifestations of the Tathāgatagarbha — what the ancients called \"radiating light and shaking the earth at the gates of the six senses.\" Once you know which features are manifestations of the Tathāgatagarbha, you abide in that feature and let time continue.</p><p>So the first step is: someone points out to you which features are manifestations of the Tathāgatagarbha. Through such pointing, again and again, you finally realize — oh, so these features are manifestations of the Tathāgatagarbha. What is this called? It is called clarifying the mind, breaking the first barrier. You have passed the first gate: you now know how to apply effort, how the mind should be used, and how practice should proceed. This is only the first gate.</p><p>What do you do in the second gate? You must abide exclusively in this feature, and through this feature you return to the Tathāgatagarbha. Only this is true great awakening — only returning to the Tathāgatagarbha is great awakening. The earlier step was merely clarifying the mind; the later step is returning to the Tathāgatagarbha. We speak of \"clarifying the mind and seeing one's nature.\" Once this gate is passed, it is called completing the return of thinking — that is, we have entered the Tathāgatagarbha.</p><p>The aspect of thinking is resolved, but you have not yet truly mastered the application of matter, so there is one final step: you must complete the application of matter, which is entering the eighth stage. The last is called \"a further step beyond the top of the hundred-foot pole.\" Without this final step it will not do, and you will not succeed. In other words, the practice of Chan proceeds through these three steps according to this same principle.</p><p>As you can see, these three steps are the same as general Buddhist practice: first one enters the first stage, first returns to the Tathāgatagarbha, and then enters the eighth stage, attains the mind-made body, and gains freedom of matter. This is the most fundamental principle of empirical practice. You must grasp it; once you do, you will know what to do.</p>",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  },
  {
    "body": "<p>佛学以其科学的实证精神，使后来的人们能够通过对佛学的学习，得到心理上的根本解脱，同时也使身体得到最大限度的康复，正是因为佛学心地法门对人类身心健康的卓有成效的探索，使得我们现代人能在这物欲横流的享受主义盛行的时代，得到一份世外桃源般的清凉，找到一个心灵的避风港。下面就借助上图系统讲述一下佛学的核心理论：心地法门。</p><p>上图是一个双层灯笼，里面的烛光，代表我们心理的本来状态，也就是我们常说的真心、如来藏、本来面目、菩提、禅、真如、如如、觉、大悲心、自性等等。外面的两层灯笼纸，红色的代表第六识意识，绿色的代表第七识末那识。</p><p>第六识意识指的是心理活动的相续性，比如你对某人一见钟情，你会控制不住的茶里饭里都是他，心就像脱缰的野马一样停不下来，这就是意的相续性。而第七识则是分别执着识，你吃饭的时候总要忍不住分别好吃还是不好吃，好吃的你就忍不住要喜欢，当然不好吃的你会如食锯末、味同嚼蜡，这就是分别执着。图上箭头代表我们实证过程中的心路历程。</p><p>我们平常的人就生活在灯笼外面的心理状态，清净无染的心光从里面透出来，经过六七两识的污染，就变成了红绿两种颜色，这就迫使你不得不成为心的奴隶，任凭心理咨询师怎样善说六国的剖析解释，任凭阿Q怎样无敌的法宝精神胜利法，对你都无济于事，因为你毕竟处在水生火热中，那些人不过是在岸上鼓励你要挺住，画饼岂能充饥，望梅真的能止渴么？受过巨大心灵创伤的人最能体会心死的感觉。</p><p>怎样使自己能够自主心灵呢？怎样能够使自己真的成为自己心理活动的主人呢？这就是佛学心地法门的根本任务。这里简要介绍一下方法，如果有兴趣深究，我们其他的几篇文章可以作为参考。</p><p>第一步 培养专注力。持续的长时间的专心致志的观想一个动作或一个物体，也可以听一种声音等等都可以。就这样渐次达到一种毫无身体感觉的状态。到了这时候，你就会很清楚的看到前一个念头下去，隔了一会后一个念头才会出来。念头的相续性彻底被消灭了，也就是说意根伏下了。</p><p>第二步 接上面，每出一个念头，你都要清清楚楚的看到它，然后用轻柔的心放下它，你会发现念头与念头之间的时间距离越来越长。这时候你用无我的思想想象把自己和整个大自然融合在一起，你会发现念头没有了，而你心里却清清楚楚，思想很活跃，你终于第一次体会到念头和思想并不总是一回事，你同时还会发现你再也不会生气了，尽管你试图是自己再生气起来，但你发现那是多么困难的一件事。</p><p>第三步 达到第二步的人往往很怀念以前能生气的状态，这就是习气，他于是竭尽全力去想象生气是怎麽一回事，进过一番刻苦和努力，终于他发现一种心力明显动起来，紧跟着就产生第一个念头“我”，紧接着就是“他”，随后就是成对成对相互对立的念头相续出现，比如爱与恨、喜欢与厌恶等，这就是第七识，发展下去你会盯着一件印象最深的具体的事情连续地想下去，这就是第六识，你终于又回到以前的病态心理活动状态中了。</p><p>这就是佛学整个心地法门的心路历程，它难道不是一副治疗心理疾病的良药吗？它能从根本上治疗你的心理疾病，让你做自己心灵的主人，这是任何通常意义上的心理学所无法做到的。</p>",
    "category": "心地法门",
    "cover": "",
    "created": "2026-08-13 08:27:00.492Z",
    "excerpt": "清凉月老师以双层灯笼为喻，系统讲解佛学心地法门：真心如烛光，第六识意识与第七识末那识如灯笼纸，实证即是从污染心念回归清净心光的完整心路历程。",
    "historical": "",
    "id": "edldz4hl0whcebw",
    "metaDescription": "Using the metaphor of a double-layered lantern, Qingliangyue systematically explains the Buddhist mind-ground method: the true mind is like the candle flame within, while the sixth consciousness and the seventh consciousness are like the lantern paper. Practice is the complete inner journey from defiled thoughts back to the pure light of mind.",
    "ogImage": "",
    "overview": "本文为清凉月老师关于佛学心地法门的原创概述。佛学以科学的实证精神，助人获得心理的根本解脱与身体的康复。文章以双层灯笼为喻：烛光代表真心、如来藏，红绿两层灯笼纸分别代表第六识意识与第七识末那识，并分三步讲述从培养专注力、放下念头到体会念头与思想之别的心路历程。",
    "publishAt": "2026-08-13 08:27:00.000Z",
    "related": "qingliangyue-zhiguan-intro,qingliangyue-chan-steps",
    "seoTitle": "The Essentials of Buddhism: The Mind-Ground Method — Practitioner Writings | Spirit Root",
    "slug": "qingliangyue-xindi-famen",
    "status": "published",
    "tags": "佛学,心地法门,专注力,如来藏,清凉月",
    "title": "佛学要旨，心地法门",
    "type": "wiki",
    "updated": "2026-08-13 08:27:00.492Z",
    "author": "qingliangyue",
    "titleEn": "The Essentials of Buddhism: The Mind-Ground Method",
    "categoryEn": "Mind-Ground Method",
    "tagsEn": "Buddhism,Mind-Ground,Concentration,Tathāgatagarbha,Qingliangyue",
    "excerptEn": "Using the metaphor of a double-layered lantern, Qingliangyue systematically explains the Buddhist mind-ground method: the true mind is like the candle flame within, while the sixth consciousness and the seventh consciousness are like the lantern paper. Practice is the complete inner journey from defiled thoughts back to the pure light of mind.",
    "overviewEn": "This is an original overview by Qingliangyue on the Buddhist mind-ground method. With its scientific spirit of empirical practice, Buddhism helps one attain fundamental liberation of mind and recovery of body. Using the metaphor of a double-layered lantern — the candle flame as the true mind and Tathāgatagarbha, the red and green lantern paper as the sixth and seventh consciousnesses — the article describes in three steps the inner journey from cultivating concentration, to releasing thoughts, to experiencing the difference between thoughts and awareness.",
    "bodyEn": "<p>With its scientific spirit of empirical practice, Buddhism enables later generations to attain fundamental liberation of mind through the study of Buddhism, and at the same time to bring about the greatest possible recovery of the body. It is precisely because the Buddhist mind-ground method has carried out such fruitful exploration of human physical and mental health that we modern people, in an age awash with material desire and the prevalence of hedonism, can obtain a tranquility like that of a utopian refuge and find a safe haven for the mind. Let us now use the diagram above to systematically explain the core theory of Buddhism: the mind-ground method.</p><p>The diagram above is a double-layered lantern. The candle flame inside represents the original state of our mind — what we commonly call the true mind, the Tathāgatagarbha, the original face, bodhi, Chan, true thusness, suchness, awareness, the mind of great compassion, self-nature, and so on. The two outer layers of lantern paper represent the sixth consciousness (consciousness, red) and the seventh consciousness (manas, green).</p><p>The sixth consciousness refers to the continuity of mental activity. For example, when you fall in love at first sight with someone, you cannot help thinking of them in everything you do — your mind is like a runaway horse that cannot stop. This is the continuity of consciousness. The seventh consciousness is the discriminating and clinging consciousness: when you eat, you cannot help distinguishing between delicious and not delicious; what is delicious you cannot help liking, while what is not delicious feels like chewing sawdust — this is discrimination and clinging. The arrows in the diagram represent the inner journey of our empirical practice.</p><p>We ordinary people live in the mental state on the outside of the lantern. The pure, undefiled light of mind shines from within, but after passing through the contamination of the sixth and seventh consciousnesses it becomes the two colors red and green. This forces you to become a slave of your mind. No matter how eloquently a psychological counselor analyzes and explains, and no matter how invincible Ah Q's spiritual victory method may be, none of it helps you — because you are, after all, in deep water and hot fire; those people are merely on the shore encouraging you to hold on. Can a painted pie satisfy hunger? Can gazing at plums truly quench thirst? Those who have suffered great psychological trauma know best the feeling of a dead heart.</p><p>How can one become master of one's own mind? How can one truly become the master of one's own mental activity? This is the fundamental task of the Buddhist mind-ground method. Here is a brief introduction to the method; if you wish to delve deeper, several of our other articles may serve as references.</p><p>Step One: Cultivate concentration. Continuously and for a long time, single-mindedly contemplate one action or one object, or listen to a sound, and so on. In this way, gradually reach a state in which there is no bodily sensation at all. At this point, you will clearly see one thought subside, and only after a gap will the next thought arise. The continuity of thoughts is completely eliminated — in other words, the faculty of consciousness is subdued.</p><p>Step Two: Continuing from above, each time a thought arises, you must see it with perfect clarity, then release it with a gentle mind. You will find that the interval between thoughts grows longer and longer. At this point, use the thought of selflessness to imagine merging yourself with all of nature. You will find that thoughts disappear, yet your mind remains perfectly clear and your awareness is very active. For the first time, you realize that thoughts and awareness are not always the same thing. At the same time, you will find that you can no longer get angry — even if you try to make yourself angry again, you discover how difficult that is.</p><p>Step Three: Those who have reached the second step often miss the former state in which they could get angry — this is habitual tendency. So they exert all their effort to imagine what anger is like. After a period of arduous effort, they finally find that a mental force clearly begins to move, immediately followed by the first thought, \"I,\" then \"he,\" and then pairs of opposing thoughts arise in succession — love and hate, liking and dislike, and so on. This is the seventh consciousness. As it develops, you will fixate on one specific, most impressive matter and think about it continuously — this is the sixth consciousness. You have finally returned to the former state of pathological mental activity.</p><p>This is the entire inner journey of the Buddhist mind-ground method. Is it not a fine medicine for treating psychological illness? It can cure your psychological illness at its root and let you become the master of your own mind — something that no ordinary psychology can accomplish.</p>",
    "collectionId": "articles",
    "collectionName": "articles",
    "expand": {}
  }
];
export default articlesData;
